# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Column_2', models.IntegerField(db_column='word')),
                ('Column_3', models.IntegerField(db_column='frequency')),
            ],
        ),
    ]
