# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtext', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='Column_2',
        ),
        migrations.RemoveField(
            model_name='words',
            name='Column_3',
        ),
        migrations.AddField(
            model_name='words',
            name='frequency',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='word',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
