# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtext', '0002_auto_20190810_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='words',
            name='word',
        ),
        migrations.AddField(
            model_name='words',
            name='Column_2',
            field=models.CharField(db_column='word', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='Column_3',
            field=models.IntegerField(db_column='frequency', null=True),
        ),
    ]
